### ISSUE TITLE
How to stop watching?

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#38] opened 2020-11-02 12:05 UTC
Hi,
What should I do if I want to stop watching?
If I set to CURLOPT_TIMEOUT_MS, applications will receive the entire object state once again whenever they call watch after timeout. 
This is not WATCH but the same as calling GET repeatedly.
If I kill the watch thread with pthread_cancel(), we will have the problem of leaking resources.
We leak curl handle, curl mime, apiClient, cJSON_Parse in wu_convert_to_json_array() and so on.
How can I gracefully exit on curl_easy_perform()? 
How can I stop the watch without resource leak?
Please consider about it.
Thanks in advance.

**Comment by ityuhui** [comment] 2020-11-02 12:41
I think the best way is setting a timetout in the parameter of watch function, after timeouts, free up the resource same with non-watch example.

e.g.
```c
    CoreV1API_listNamespacedPod(apiClient, "default",   /*namespace */
                                NULL,   /* pretty */
                                0,  /* allowWatchBookmarks */
                                NULL,   /* continue */
                                NULL,   /* fieldSelector */
                                NULL,   /* labelSelector */
                                0,  /* limit */
                                NULL,   /* resourceVersion */
                                30,  /* timeoutSeconds */     <------------------ Set the timeout
                                1   /* watch */
        );
```

**Comment by clearday4** [comment] 2020-11-02 12:47
> I think the best way is setting a timetout in the parameter of watch function, after timeouts, free up the resource same with non-watch example.
> 
> e.g.
> 
> ```c
>     CoreV1API_listNamespacedPod(apiClient, "default",   /*namespace */
>                                 NULL,   /* pretty */
>                                 0,  /* allowWatchBookmarks */
>                                 NULL,   /* continue */
>                                 NULL,   /* fieldSelector */
>                                 NULL,   /* labelSelector */
>                                 0,  /* limit */
>                                 NULL,   /* resourceVersion */
>                                 30,  /* timeoutSeconds */     <------------------ Set the timeout
>                                 1   /* watch */
>         );
> ```

Application want to watch the events util they stop watching.
They want to receive the state of the only changed object.
But if we set the timeout, application should watch again and get the entire status of object again.
what is the difference from get function?

**Comment by ityuhui** [comment] 2020-11-02 13:28
When ```timeout``` is set, watch function will not return even though it receives the state change. 

The watch function returns only the timeout is reached.

**Comment by clearday4** [comment] 2020-11-03 01:15
It doesn't meet our requirement.
application wants to know immediately if pod is scaled in or out or deleted or modified.

**Comment by ityuhui** [comment] 2020-11-03 02:36
Suppose setting a timeout such as 3600 seconds (1 hour), 
Watch function can receive events such as pod deletion/modification immediately but it will not stop watching. After 3600 seconds, the watch function will return and stop watching.

**Comment by clearday4** [comment] 2020-11-03 04:11
But After 1 hour,
if application call watch function again, K8s API server send the all pod state again,
Therefore, if application knows the pod status has changed, compared to previous status and the previous information should be stored to db

**Comment by ityuhui** [comment] 2020-11-03 04:34
I think you can set a longer timeout.
Or run watch function forever in a thread. After the program ends, allocated memory will be released.

And I see you have tried ```pthread_cancel()```, then when will you call ```pthread_cancel()``` ?

**Comment by clearday4** [comment] 2020-11-03 06:52
If I kill the watch thread with pthread_cancel, resource leak occurs.
Since watch thread is blocked on curl_easy_perform, curl handle, curl mime, apiClient and cJSON_Parse are leak

**Comment by ityuhui** [comment] 2020-11-03 06:54
Could you please run watch function forever in a thread ?
After the program ends, allocated memory will be released.

**Comment by clearday4** [comment] 2020-11-03 07:31
right. so application can't stop watching until now.

**Comment by brendandburns** [comment] 2020-11-05 18:37
Can't you use `pthread_cleanup_push` to register a cleanup handler for the watch `pthread`?

https://man7.org/linux/man-pages/man3/pthread_cleanup_push.3.html

**Comment by brendandburns** [comment] 2020-11-30 17:34
I'm closing this since I think that the issue issue is resolved via the Libcurl progress functions.

**Comment by brendandburns** [comment] 2020-11-30 17:35
Please use `/reopen` if there is further assistance needed.

**Closed by brendandburns** 2020-11-30 17:34 UTC
